/* Generated by Pyrex 0.9.4.1 on Wed Jul  5 17:34:21 2006 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "stdlib.h"
#include "srilmwrap.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

/* Declarations from srilmwrap */


/* Declarations from srilm */


struct __pyx_obj_5srilm_Vocab {
  PyObject_HEAD
  Vocab (*vocab);
};


struct __pyx_obj_5srilm_Ngram {
  PyObject_HEAD
  Ngram (*ngram);
  struct __pyx_obj_5srilm_Vocab *vocab;
  int order;
};

static PyTypeObject *__pyx_ptype_5srilm_Vocab = 0;
static PyTypeObject *__pyx_ptype_5srilm_Ngram = 0;
static int __pyx_v_5srilm_bufsize;
static int (*__pyx_v_5srilm_buf);
static int __pyx_v_5srilm_NONE;
static PyObject *__pyx_k1;

/* Implementation of srilm */

static PyObject *__pyx_n_srilmwrap;
static PyObject *__pyx_n_False;

static int __pyx_f_5srilm_5Vocab___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5srilm_5Vocab___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":20 */
  ((struct __pyx_obj_5srilm_Vocab *)__pyx_v_self)->vocab = new_vocab();

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("srilm.Vocab.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_5srilm_5Vocab___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_5srilm_5Vocab___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":23 */
  vocab_delete(((struct __pyx_obj_5srilm_Vocab *)__pyx_v_self)->vocab);

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("srilm.Vocab.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_5srilm_5Vocab_word(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5srilm_5Vocab_word(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"i",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_i)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":26 */
  __pyx_1 = PyString_FromString(vocab_word(((struct __pyx_obj_5srilm_Vocab *)__pyx_v_self)->vocab,__pyx_v_i)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("srilm.Vocab.word");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_5srilm_5Vocab_index(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5srilm_5Vocab_index(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_s);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"s",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_s)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":29 */
  __pyx_1 = PyInt_FromLong(vocab_index(((struct __pyx_obj_5srilm_Vocab *)__pyx_v_self)->vocab,__pyx_v_s)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("srilm.Vocab.index");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_5srilm_5Ngram___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5srilm_5Ngram___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_5srilm_Vocab *__pyx_v_vocab = 0;
  int __pyx_v_order;
  int __pyx_r;
  static char *__pyx_argnames[] = {"vocab","order",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "Oi", __pyx_argnames, &__pyx_v_vocab, &__pyx_v_order)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_vocab);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_vocab), __pyx_ptype_5srilm_Vocab, 1, "vocab")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":46 */
  Py_INCREF(((PyObject *)__pyx_v_vocab));
  Py_DECREF(((PyObject *)((struct __pyx_obj_5srilm_Ngram *)__pyx_v_self)->vocab));
  ((struct __pyx_obj_5srilm_Ngram *)__pyx_v_self)->vocab = __pyx_v_vocab;

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":47 */
  ((struct __pyx_obj_5srilm_Ngram *)__pyx_v_self)->ngram = new_ngram(__pyx_v_vocab->vocab,__pyx_v_order);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":48 */
  ((struct __pyx_obj_5srilm_Ngram *)__pyx_v_self)->order = __pyx_v_order;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("srilm.Ngram.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_vocab);
  return __pyx_r;
}

static int __pyx_f_5srilm_5Ngram___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5srilm_5Ngram___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_vocab = 0;
  PyObject *__pyx_v_order = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"vocab","order",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_vocab, &__pyx_v_order)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_vocab);
  Py_INCREF(__pyx_v_order);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":51 */

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("srilm.Ngram.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_vocab);
  Py_DECREF(__pyx_v_order);
  return __pyx_r;
}

static void __pyx_f_5srilm_5Ngram___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_5srilm_5Ngram___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":54 */
  ngram_delete(((struct __pyx_obj_5srilm_Ngram *)__pyx_v_self)->ngram);

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("srilm.Ngram.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n_IOError;

static PyObject *__pyx_k2p;

static char (__pyx_k2[]) = "Couldn't read LM file";

static PyObject *__pyx_f_5srilm_5Ngram_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5srilm_5Ngram_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_filename = 0;
  PyObject *__pyx_v_limit_vocab = 0;
  PyObject *__pyx_r;
  char (*__pyx_1);
  int __pyx_2;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"filename","limit_vocab",0};
  __pyx_v_limit_vocab = __pyx_k1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_filename, &__pyx_v_limit_vocab)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_filename);
  Py_INCREF(__pyx_v_limit_vocab);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":57 */
  __pyx_1 = PyString_AsString(__pyx_v_filename); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_limit_vocab); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  __pyx_3 = (!ngram_read(((struct __pyx_obj_5srilm_Ngram *)__pyx_v_self)->ngram,__pyx_1,__pyx_2));
  if (__pyx_3) {

    /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":58 */
    __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __Pyx_Raise(__pyx_4, __pyx_k2p, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("srilm.Ngram.read");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_filename);
  Py_DECREF(__pyx_v_limit_vocab);
  return __pyx_r;
}

static PyObject *__pyx_n_len;

static PyObject *__pyx_f_5srilm_5Ngram_wordprob(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5srilm_5Ngram_wordprob(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_word;
  PyObject *__pyx_v_context = 0;
  int __pyx_v_length;
  int __pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {"word","context",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "iO", __pyx_argnames, &__pyx_v_word, &__pyx_v_context)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_context);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":63 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  Py_INCREF(__pyx_v_context);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_context);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_length = __pyx_4;

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":64 */
  while (1) {
    __pyx_L2:;
    __pyx_4 = ((__pyx_v_length + 1) > __pyx_v_5srilm_bufsize);
    if (!__pyx_4) break;

    /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":65 */
    __pyx_v_5srilm_bufsize = (__pyx_v_5srilm_bufsize * 2);

    /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":66 */
    __pyx_v_5srilm_buf = ((int (*))realloc(__pyx_v_5srilm_buf,(__pyx_v_5srilm_bufsize * (sizeof(int )))));
  }
  __pyx_L3:;

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":68 */
  (__pyx_v_5srilm_buf[__pyx_v_length]) = __pyx_v_5srilm_NONE;

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":69 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_length; ++__pyx_v_i) {

    /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":70 */
    __pyx_1 = PyInt_FromLong(__pyx_v_i); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
    __pyx_2 = PyObject_GetItem(__pyx_v_context, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    (__pyx_v_5srilm_buf[((__pyx_v_length - __pyx_v_i) - 1)]) = __pyx_4;
    __pyx_L4:;
  }
  __pyx_L5:;

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":71 */
  __pyx_3 = PyFloat_FromDouble(ngram_wordProb(((struct __pyx_obj_5srilm_Ngram *)__pyx_v_self)->ngram,__pyx_v_word,__pyx_v_5srilm_buf)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("srilm.Ngram.wordprob");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_context);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_False, "False"},
  {&__pyx_n_IOError, "IOError"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_srilmwrap, "srilmwrap"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_5srilm_Vocab(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5srilm_Vocab *p = (struct __pyx_obj_5srilm_Vocab *)o;
  if (__pyx_f_5srilm_5Vocab___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_5srilm_Vocab(PyObject *o) {
  struct __pyx_obj_5srilm_Vocab *p = (struct __pyx_obj_5srilm_Vocab *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_5srilm_5Vocab___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5srilm_Vocab(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5srilm_Vocab *p = (struct __pyx_obj_5srilm_Vocab *)o;
  return 0;
}

static int __pyx_tp_clear_5srilm_Vocab(PyObject *o) {
  struct __pyx_obj_5srilm_Vocab *p = (struct __pyx_obj_5srilm_Vocab *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_5srilm_Vocab[] = {
  {"word", (PyCFunction)__pyx_f_5srilm_5Vocab_word, METH_VARARGS|METH_KEYWORDS, 0},
  {"index", (PyCFunction)__pyx_f_5srilm_5Vocab_index, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Vocab = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Vocab = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Vocab = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Vocab = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_5srilm_Vocab = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "srilm.Vocab", /*tp_name*/
  sizeof(struct __pyx_obj_5srilm_Vocab), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5srilm_Vocab, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Vocab, /*tp_as_number*/
  &__pyx_tp_as_sequence_Vocab, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Vocab, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Vocab, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_5srilm_Vocab, /*tp_traverse*/
  __pyx_tp_clear_5srilm_Vocab, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5srilm_Vocab, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5srilm_Vocab, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_5srilm_Ngram(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5srilm_Ngram *p = (struct __pyx_obj_5srilm_Ngram *)o;
  p->vocab = ((struct __pyx_obj_5srilm_Vocab *)Py_None); Py_INCREF(Py_None);
  if (__pyx_f_5srilm_5Ngram___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_5srilm_Ngram(PyObject *o) {
  struct __pyx_obj_5srilm_Ngram *p = (struct __pyx_obj_5srilm_Ngram *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_5srilm_5Ngram___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(((PyObject *)p->vocab));
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5srilm_Ngram(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5srilm_Ngram *p = (struct __pyx_obj_5srilm_Ngram *)o;
  if (p->vocab) {
    e = (*v)(((PyObject*)p->vocab), a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_5srilm_Ngram(PyObject *o) {
  struct __pyx_obj_5srilm_Ngram *p = (struct __pyx_obj_5srilm_Ngram *)o;
  Py_XDECREF(((PyObject *)p->vocab));
  p->vocab = ((struct __pyx_obj_5srilm_Vocab *)Py_None); Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_5srilm_Ngram[] = {
  {"read", (PyCFunction)__pyx_f_5srilm_5Ngram_read, METH_VARARGS|METH_KEYWORDS, 0},
  {"wordprob", (PyCFunction)__pyx_f_5srilm_5Ngram_wordprob, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Ngram = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Ngram = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Ngram = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Ngram = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_5srilm_Ngram = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "srilm.Ngram", /*tp_name*/
  sizeof(struct __pyx_obj_5srilm_Ngram), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5srilm_Ngram, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Ngram, /*tp_as_number*/
  &__pyx_tp_as_sequence_Ngram, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Ngram, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Ngram, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_5srilm_Ngram, /*tp_traverse*/
  __pyx_tp_clear_5srilm_Ngram, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5srilm_Ngram, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_5srilm_5Ngram___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5srilm_Ngram, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initsrilm(void); /*proto*/
PyMODINIT_FUNC initsrilm(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("srilm", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_5srilm_Vocab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Vocab", (PyObject *)&__pyx_type_5srilm_Vocab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  __pyx_ptype_5srilm_Vocab = &__pyx_type_5srilm_Vocab;
  __pyx_type_5srilm_Ngram.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_5srilm_Ngram) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Ngram", (PyObject *)&__pyx_type_5srilm_Ngram) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_ptype_5srilm_Ngram = &__pyx_type_5srilm_Ngram;

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":34 */
  __pyx_v_5srilm_bufsize = 5;

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":35 */
  __pyx_v_5srilm_buf = ((int (*))malloc(__pyx_v_5srilm_bufsize));

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":38 */
  __pyx_v_5srilm_NONE = (-1);

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":56 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_k1 = __pyx_1;
  __pyx_1 = 0;

  /* "/auto/hpc-22/dmarcu/nlg/chiangd/psrilm/srilm.pyx":60 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("srilm");
}

static char *__pyx_filenames[] = {
  "srilm.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
